name: NIPM 23.8 Docker Image

on:
  push:
    branches: [ "main" ]
    paths: 'src/NIPM/23.8/**'
  pull_request:
    branches: [ "main" ]
    paths: 'src/NIPM/23.8/**'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Docker image for NIPM 23.8
      run: docker build --rm -f ".\src\NIPM\23.8\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/nipm:23.8 ".\src\NIPM\23.8"
    - name: Push Docker image for NIPM 23.8
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/nipm
