name: NIPM Docker Image Layer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: docker build --rm -f ".\src\NIPM\22.8\Dockerfile" `
           -t ${{ secrets.DOCKERHUB_USERNAME }}/nipm:22.8 `
           ".\src\NIPM\22.8"
      
    
