name: NIPM Docker Image Layer

on:
  push:
    branches: [ "main/src/NIPM" ]
  pull_request:
    branches: [ "main/src/NIPM" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Docker image for NIPM 22.8
      run: docker build --rm -f ".\src\NIPM\22.8\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/nipm:22.8 ".\src\NIPM\22.8"
    - name: Push Docker image for NIPM 22.8
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/nipm
