name: VI Analyzer Docker Image Layer

on:
  push:
    branches: [ "main/src/VIAnalyzer" ]
  pull_request:
    branches: [ "main/src/VIAnalyzer" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Docker image for VIAnalyzer 21.0 32bit
      run: docker build --rm -f ".\src\VIAnalyzer\32bit\21.0\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/vian:21.0-32bit ".\src\VIAnalyzer\32bit\21.0"
    - name: Push Docker image for VIAnalyzer 21.0 32bit
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/vian
    
