name: UTF Docker Image Layer

on:
  push:
    branches: [ "main" ]
    paths: 'src/UTF/**'
  pull_request:
    branches: [ "main" ]
    paths: 'src/UTF/**'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Docker image for UTF 21.0 32bit
      run: docker build --rm -f ".\src\UTF\32bit\21.0\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/utf:21.0-32bit ".\src\UTF\32bit\21.0"
    - name: Push Docker image for UTF 21.0 32bit
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/utf
    
