name: FULL Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Docker image for NIPM 22.8
      run: docker build --rm -f ".\src\NIPM\22.8\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/nipm:22.8 ".\src\NIPM\22.8"
    - name: Push Docker image for NIPM 22.8
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/nipm

    - name: Build Docker image for LabVIEW 21.0 32bit
      run: docker build --rm -f ".\src\LabVIEW\32bit\21.0\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/labview:21.0-32bit ".\src\LabVIEW\32bit\21.0"
    - name: Push Docker image for LabVIEW 21.0 32bit
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/labview

    - name: Build Docker image for VIAnalyzer 21.0 32bit
      run: docker build --rm -f ".\src\VIAnalyzer\32bit\21.0\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/vian:21.0-32bit ".\src\VIAnalyzer\32bit\21.0"
    - name: Push Docker image for VIAnalyzer 21.0 32bit
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/vian

    - name: Build Docker image for UTF 21.0 32bit
      run: docker build --rm -f ".\src\UTF\32bit\21.0\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/utf:21.0-32bit ".\src\UTF\32bit\21.0"
    - name: Push Docker image for UTF 21.0 32bit
      run: docker image push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/utf
    
