name: NIPM Docker Image Layer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
            
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./src/NIPM/22.8
        push: true
        tags: danyallard/nipm-22.8:$(date +%s)
    
